version: "3.8"

services:
  auth-service.integration.test:
    container_name: varnex-auth-integration-test
    build:
      context: ../test/Varnex.AuthService.Integration.Test
      dockerfile: Dockerfile.test
    depends_on:
      auth-service:
        condition: service_healthy
    environment:
      - AUTH_BASE_URL=http://auth-service
    networks:
      - varnex-auth-network

networks:
  varnex-auth-network:
    driver: bridge
